version: '3.8'
services:
  mlenv:
    build:
      context: .
      args:
        version: "latest-gpu"
    #user: ${UID:-1000}:${GID:-1000}
    #command: bash
    volumes:
      # - type: volume
      #   source: bridge
      #   target: /home/ml_env_vol
      #   volume:
      #     nocopy: false
      - type: bind
        source: ./
        target: /home/ml_env_bridge
    #stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

# volumes:
#   bridge:
