version: '3.8'
services:
  mlenv:
    build:
      context: .
      args:
        version: "latest-gpu"
    command: bash
    volumes:
      - bridge:/ml_env_bridge
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
volumes:
  bridge:
