# This assumes the container is running on a system with a CUDA GPU
FROM tensorflow/tensorflow:latest-gpu

WORKDIR /ml_env_bridge

RUN pip install -r requirements.txt

#EXPOSE 8888

#ENTRYPOINT ["code", "."]